const mongoose = require('mongoose');

const { Schema } = mongoose;

const ProtocoloSchema = new Schema({
        Fecha: Date, 
        Protocolo: Number, 
        Observacion: String,
        Urgente: String, 
        Paciente: {
            Nombre: String,
            DNI: Number,
            Edad: Number, 
            Sexo: String,
            FecNac: Date,
            Provincia: String,
            Departamento: String,
            Localidad: String,
            Barrio: String,
            Calle: String,
            Nro: String,
            TelCasa: String,
            TelCelular: String,
        }, 
        Hemograma: {
            Eritrocitos: String,
            Hemoglobina: String,
            Hematocritos: String,
            Leucocitos: String,
            Plaquetas: String,
            Eritrosedimentacion: String,
        }, 
        Formula_Leucocitaria: {
            Neutrofilos_en_cayados: String,
            Neutrofilos_segmentados: String,
            Eosinofilos: String,
            Basofilos: String,
            Linfocitos: String,
            Monocitos: String,
            Alteraciones: String,
        }, 
        Orina: {
            Color: String,
            Aspecto: String,
            pH: String,
            Densidad: String,
            Proteinas: String,
            Glucosa: String,
            C_Cetonicos: String,
            Pigm_Biliares: String,
            Hemoglobina: String,
        }, 
        Examen_Microscopico_de_Sedimento: {
            Celulas: String,
            Leucocitos: String,
            Hematies: String,
            Cilindros: String,
            Cristales: String,
            Bacteriuria: String,
            Mucus: String,
            Observaciones: String,
        }, 
        Sedimento_urinario: {
            Recuento_de_Colonias: String,
            Tipificacion: String,
        }, 
        Antibiograma: {
            Sensibles: String,
            Resistentes: String,
            Observaciones: String,
        }, 
        Analisis_quimico: {
            Glucemia: String,
            Uremia: String,
            Colesterol: String,
            HDL_colesterol: String,
            LDL_colesterol: String,
            Trigliceridos : String, 
            Calcemia : String,
            Acido_Urico: String,
            Creatinina: String,
            indice_proteinuria_creatininuria: String,
            MDRD_4_IDMS: String,
            Proteinas_Totales: String,
            Albumina: String,
        }, 
        Enzimas: {
            GOT: String,
            GPT: String,
            Fosfatasa_Alc: String,
            GammaGT: String,
            Amilasa: String,
        }, 
        Bilirrubina: {
            Total: String,
            Directa: String,
            Indirecta: String,
        }, 
        Coagulacion: {
            Protrombina: String,
            Actividad: String,
            KPTT: String,
        }, 
        PRUEBA_DE_TOLERANCIA_ORAL_A_LA_GLUCOSA: {
            Glucemia_en_ayunas: String,
            Glucemia_a_los_60_min_post_sobrecarga: String,
            Glucemia_a_los_120_minutos_post_sobrecarga: String,
        }, 
        Grupo_Sanguineo: String,
        Factor_RH: String,
        Serologia: {
            VDRL: String,
            PRUEBA_TREPONEMICA: String,
            Chagas_HAI_y_ELISA: String,
            Chagas_HAI: String,
            Chagas_ELISA: String,
            Huddleson: String,
            Toxoplasmosis_AD: String,
            HIV_AP: String,
            HBsAg: String,
            HCV: String,
            Toxoplasmosis_IGM: String,
            AELO: String,
            Artritest: String,
            Proteina_C_Reactiva: String,
        }, 
        HCG_EN_SANGRE: String,
        PSA_prostatico: String,
        POLIMORFOS_NUCLEARES_EN_MATERIA_FECAL: String,
        COPROPARASITOLOGICO_SERIADO: String,
        ESCOBILLADO_ANAL: String,
        PROTEINURIA_24_hs: String,
        EXUDADO_VAGINAL_ANAL: String,
        HbA1c_hemoglobina_glicosilada: String,
        TIROIDE_TSH: String,
        TIROIDE_T4: String,
        STROUT: String,
        IGA_TGG_celiuaquia: String,
        SOMF_sangre_oculta_en_materia_fecal: String,
        IONOGRAMA: {
            cNa: String,
            cK: String,
            cCl: String,
            cCa: String,
        }
});

module.exports = mongoose.model('Protocolo', ProtocoloSchema);