const mongoose = require('mongoose');

const { Schema } = mongoose;

const ProtocoloSchema = new Schema({
        Fecha: Date, 
        Protocolo: Number, 
        Observacion: String,
        Urgente: String, 
        Paciente: {
            Nombre: String,
            DNI: Number,
            Edad: Number, 
            Sexo: String,
            FecNac: Date,
            Provincia: String,
            Departamento: String,
            Localidad: String,
            Barrio: String,
            Calle: String,
            Nro: String,
            TelCasa: String,
            TelCelular: String,
        }, 
        Hemograma: {
            Eritrocitos: String,
            Hemoglobina: String,
            Hematocritos: String,
            Leucocitos: String,
            Plaquetas: String,
            Eritrosedimentacion: String,
        }, 
        "Formula Leucocitaria": {
            "Neutrofilos en cayados": String,
            "Neutrofilos segmentados": String,
            Eosinofilos: String,
            Basofilos: String,
            Linfocitos: String,
            Monocitos: String,
            Alteraciones: String,
        }, 
        Orina: {
            Color: String,
            Aspecto: String,
            pH: String,
            Densidad: String,
            Proteinas: String,
            Glucosa: String,
            "C_ Cetonicos": String,
            "Pigm_ Biliares": String,
            Hemoglobina: String,
        }, 
        "Examen Microscopico de Sedimento": {
            Celulas: String,
            Leucocitos: String,
            Hematies: String,
            Cilindros: String,
            Cristales: String,
            Bacteriuria: String,
            Mucus: String,
            Observaciones: String,
        }, 
        "Sedimento urinario": {
            "Recuento de Colonias": String,
            Tipificacion: String,
        }, 
        Antibiograma: {
            Sensibles: String,
            Resistentes: String,
            Observaciones: String,
        }, 
        "Analisis quimico": {
            Glucemia: String,
            Uremia: String,
            Colesterol: String,
            "HDL colesterol": String,
            "Acido Urico": String,
            Creatinina: String,
            "indice proteinuria - creatininuria": String,
            "MDRD-4 IDMS": String,
            "Proteinas Totales": String,
            Albumina: String,
        }, 
        Enzimas: {
            GOT: String,
            GPT: String,
            "Fosfatasa Alc": String,
            GammaGT: String,
            Amilasa: String,
        }, 
        Bilirrubina: {
            Total: String,
            Directa: String,
            Indirecta: String,
        }, 
        Coagulacion: {
            Protrombina: String,
            Actividad: String,
            KPTT: String,
        }, 
        "PRUEBA DE TOLERANCIA ORAL A LA GLUCOSA": {
            "Glucemia en ayunas": String,
            "Glucemia a los 60 min post sobrecarga": String,
            "Glucemia a los 120 minutos post sobrecarga": String,
        }, 
        "Grupo Sanguineo": String,
        "Factor RH": String,
        Serologia: {
            VDRL: String,
            "PRUEBA TREPONEMICA": String,
            "Chagas (HAI y ELISA)": String,
            "Chagas (HAI)": String,
            "Chagas (ELISA)": String,
            Huddleson: String,
            "Toxoplasmosis (AD)": String,
            "HIV(AP)": String,
            HBsAg: String,
            HCV: String,
            "Toxoplasmosis (IGM)": String,
            AELO: String,
            Artritest: String,
            "Proteina C Reactiva": String,
        }, 
        "HCG EN SANGRE": String,
        "PSA (prostatico)": String,
        "POLIMORFOS NUCLEARES EN MATERIA FECAL": String,
        "COPROPARASITOLOGICO SERIADO": String,
        "ESCOBILLADO ANAL": String,
        "PROTEINURIA  (24 hs)": String,
        "EXUDADO VAGINAL - ANAL": String,
        "HbA1c  (hemoglobina glicosilada)": String,
        "TIROIDE (TSH)": String,
        "TIROIDE (T4)": String,
        STROUT: String,
        "IGA -TGG (celiuaquia)": String,
        "SOMF (sangre oculta en materia fecal)": String,
        IONOGRAMA: {
            "cNa+": String,
            "cK+": String,
            "cCl-": String,
            "cCa++": String,
        }
});

module.exports = mongoose.model('Protocolo', ProtocoloSchema);